"""Makefile generation and direct compilation support."""

from buildgen.makefile.variables import Var, SVar, IVar, CVar, AVar
from buildgen.makefile.generator import MakefileGenerator, MakefileWriter
from buildgen.makefile.builder import Builder
from buildgen.makefile.functions import (
    AUTOMATIC_VARIABLES,
    auto_var,
    get_auto_var_help,
    makefile_wildcard,
    makefile_patsubst,
    makefile_subst,
    makefile_filter,
    makefile_filter_out,
    makefile_sort,
    makefile_word,
    makefile_words,
    makefile_wordlist,
    makefile_firstword,
    makefile_lastword,
    makefile_dir,
    makefile_notdir,
    makefile_suffix,
    makefile_basename,
    makefile_addsuffix,
    makefile_addprefix,
    makefile_join,
    makefile_realpath,
    makefile_abspath,
    makefile_if,
    makefile_or,
    makefile_and,
    makefile_foreach,
    makefile_call,
    makefile_eval,
    makefile_origin,
    makefile_flavor,
    makefile_value,
    makefile_shell,
    makefile_strip,
    makefile_findstring,
)

__all__ = [
    # Variables
    "Var",
    "SVar",
    "IVar",
    "CVar",
    "AVar",
    # Generator
    "MakefileGenerator",
    "MakefileWriter",
    "Builder",
    # Functions
    "AUTOMATIC_VARIABLES",
    "auto_var",
    "get_auto_var_help",
    "makefile_wildcard",
    "makefile_patsubst",
    "makefile_subst",
    "makefile_filter",
    "makefile_filter_out",
    "makefile_sort",
    "makefile_word",
    "makefile_words",
    "makefile_wordlist",
    "makefile_firstword",
    "makefile_lastword",
    "makefile_dir",
    "makefile_notdir",
    "makefile_suffix",
    "makefile_basename",
    "makefile_addsuffix",
    "makefile_addprefix",
    "makefile_join",
    "makefile_realpath",
    "makefile_abspath",
    "makefile_if",
    "makefile_or",
    "makefile_and",
    "makefile_foreach",
    "makefile_call",
    "makefile_eval",
    "makefile_origin",
    "makefile_flavor",
    "makefile_value",
    "makefile_shell",
    "makefile_strip",
    "makefile_findstring",
]
