<%
_opts = context.get("options") or {}
# pure_python: no compiled extension, so nothing needs rebuilding after an edit
# and there is no CMake cache to clear.
_pure = bool(_opts.get("pure_python", False))
_kind = "pure-Python" if _pure else "scikit-build-core"
_backend = "hatchling" if _pure else "scikit-build-core"
%>\
# Makefile frontend for ${_kind} project
# Generated by buildgen for: ${name}
#
# This Makefile wraps common build commands for convenience.
# The actual build is handled by ${_backend} via pyproject.toml
#
# Assumes a virtualenv is active. Override commands with PYTHON and PIP.

.PHONY: all build install dev test lint lint-check format format-check ${"\\"}
        typecheck qa clean distclean wheel sdist dist check publish-test ${"\\"}
        publish upgrade coverage coverage-html docs release help

PYTHON ?= python
PIP ?= pip

# Default target
all: build

% if _pure:
# Editable install (pure Python: edits take effect immediately)
build:
	@$(PIP) install -ve .

# Install the package
install:
	@$(PIP) install -v .

# Development install (editable)
dev:
	@$(PIP) install -ve .
% else:
# Build the extension (in-place for development)
build:
	@$(PIP) install --no-build-isolation -ve .

# Install the package
install:
	@$(PIP) install --no-build-isolation -v .

# Development install (editable)
dev:
	@$(PIP) install --no-build-isolation -ve .
% endif

# Run tests
test: build
	@$(PYTHON) -m pytest tests/ -v

# Lint with ruff (applies fixes)
lint:
	@$(PYTHON) -m ruff check --fix src/ tests/

# Lint with ruff (check only, no fixes)
lint-check:
	@$(PYTHON) -m ruff check src/ tests/

# Format with ruff
format:
	@$(PYTHON) -m ruff format src/ tests/

# Check formatting without modifying files
format-check:
	@$(PYTHON) -m ruff format --check src/ tests/

# Type check with mypy
typecheck:
	@$(PYTHON) -m mypy src/${name}

# Run a full quality assurance check (non-mutating; mirrors CI)
qa: lint-check format-check typecheck test

# Build wheel
wheel:
	@$(PYTHON) -m build --wheel --no-isolation

# Build source distribution
sdist:
	@$(PYTHON) -m build --sdist --no-isolation

# Check distributions with twine
check:
	@$(PYTHON) -m twine check dist/*

# Build both wheel and sdist
dist: wheel sdist check

# Publish to TestPyPI
publish-test: check
	@$(PYTHON) -m twine upload --repository testpypi dist/*

# Publish to PyPI
publish: check
	@$(PYTHON) -m twine upload dist/*

# Upgrade dev dependencies
upgrade:
	@$(PIP) install --upgrade build mypy pytest pytest-cov ruff twine

# Run tests with coverage
coverage:
	@$(PYTHON) -m pytest tests/ -v --cov=src/${name} --cov-report=term-missing

# Generate HTML coverage report
coverage-html:
	@$(PYTHON) -m pytest tests/ -v --cov=src/${name} --cov-report=html
	@echo "Coverage report: htmlcov/index.html"

# Build documentation (requires sphinx; `pip install sphinx` first)
docs:
	@$(PYTHON) -m sphinx -b html docs/ docs/_build/html

# Create a release (bump version, tag, push)
release:
	@echo "Current version: $$(grep '^version' pyproject.toml | head -1)"
	@read -p "New version: " version; ${"\\"}
	sed "s/^version = .*/version = \"$$version\"/" pyproject.toml > pyproject.toml.tmp && mv pyproject.toml.tmp pyproject.toml; ${"\\"}
	git add pyproject.toml; ${"\\"}
	git commit -m "Bump version to $$version"; ${"\\"}
	git tag -a "v$$version" -m "Release $$version"; ${"\\"}
	echo "Tagged v$$version. Run 'git push && git push --tags' to publish."

# Clean build artifacts
clean:
	@rm -rf build/
	@rm -rf dist/
	@rm -rf *.egg-info/
	@rm -rf src/*.egg-info/
	@rm -rf .pytest_cache/
	@find . -name "*.so" -delete
	@find . -name "*.pyd" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

% if _pure:
# Clean everything, including tool caches
distclean: clean
	@rm -rf .mypy_cache/ .ruff_cache/
% else:
# Clean everything including CMake cache
distclean: clean
	@rm -rf CMakeCache.txt CMakeFiles/
% endif

# Show help
help:
	@echo "Available targets:"
	@echo "  all          - ${'Install in development mode' if _pure else 'Build the extension'} (default)"
	@echo "  build        - Build and install in development mode"
	@echo "  install      - Install the package"
	@echo "  dev          - Development install (editable)"
	@echo "  test         - Run tests"
	@echo "  lint         - Lint with ruff (applies fixes)"
	@echo "  lint-check   - Lint with ruff (check only)"
	@echo "  format       - Format with ruff"
	@echo "  format-check - Check formatting without modifying files"
	@echo "  typecheck    - Type check with mypy"
	@echo "  qa           - Run full quality assurance (non-mutating: lint-check, format-check, typecheck, test)"
	@echo "  wheel        - Build wheel distribution"
	@echo "  sdist        - Build source distribution"
	@echo "  dist         - Build both wheel and sdist"
	@echo "  check        - Check distributions with twine"
	@echo "  publish-test - Publish to TestPyPI"
	@echo "  publish      - Publish to PyPI"
	@echo "  upgrade      - Upgrade dev dependencies"
	@echo "  coverage     - Run tests with coverage"
	@echo "  coverage-html - Generate HTML coverage report"
	@echo "  docs         - Build documentation with Sphinx"
	@echo "  release      - Bump version, tag, and prepare release"
	@echo "  clean        - Remove build artifacts"
	@echo "  distclean    - Remove all generated files"
	@echo "  help         - Show this help message"
