# Makefile frontend for Quarto project
# Generated by buildgen for: ${name}
#
# This Makefile wraps quarto commands for convenience.

.PHONY: all render preview check clean help

# Configuration
QUARTO ?= quarto
QUARTO_FLAGS ?=
OUTPUT_DIR ?= ${output_dir}

# Default target
all: render

# Render every format listed in _quarto.yml
render:
	$(QUARTO) render $(QUARTO_FLAGS)

# Serve with live reload
preview:
	$(QUARTO) preview $(QUARTO_FLAGS)

# Verify the Quarto installation and its engines
check:
	$(QUARTO) check

# Remove rendered output and Quarto's cache (keeps _freeze/)
clean:
	@rm -rf $(OUTPUT_DIR) .quarto

# Show help
help:
	@echo "Available targets:"
	@echo "  all     - Render the project (default)"
	@echo "  render  - Render every format in _quarto.yml"
	@echo "  preview - Serve with live reload"
	@echo "  check   - Verify the Quarto installation"
	@echo "  clean   - Remove $(OUTPUT_DIR) and .quarto"
	@echo "  help    - Show this help message"
	@echo ""
	@echo "Variables:"
	@echo "  QUARTO       - Quarto executable (default: quarto)"
	@echo "  QUARTO_FLAGS - Extra flags, e.g. QUARTO_FLAGS='--to html'"
	@echo "  OUTPUT_DIR   - Rendered output directory (default: ${output_dir})"
