# Makefile frontend for a single Quarto document
# Generated by buildgen for: ${name}
#
# This Makefile wraps quarto commands for convenience.

.PHONY: all render preview check clean help

# Configuration
QUARTO ?= quarto
QUARTO_FLAGS ?=
SOURCE ?= ${name}.qmd

# Default target
all: render

# Render every format in the document header, next to the source
render:
	$(QUARTO) render $(SOURCE) $(QUARTO_FLAGS)

# Serve with live reload
preview:
	$(QUARTO) preview $(SOURCE) $(QUARTO_FLAGS)

# Verify the Quarto installation and its engines
check:
	$(QUARTO) check

# Remove rendered output and Quarto's cache
clean:
	@rm -rf ${" ".join(outputs)} ${name}_files .quarto

# Show help
help:
	@echo "Available targets:"
	@echo "  all     - Render the document (default)"
	@echo "  render  - Render every format in the document header"
	@echo "  preview - Serve with live reload"
	@echo "  check   - Verify the Quarto installation"
	@echo "  clean   - Remove rendered output"
	@echo "  help    - Show this help message"
	@echo ""
	@echo "Variables:"
	@echo "  QUARTO       - Quarto executable (default: quarto)"
	@echo "  QUARTO_FLAGS - Extra flags, e.g. QUARTO_FLAGS='--to html'"
	@echo "  SOURCE       - Document to render (default: ${name}.qmd)"
