# ${name}

This project was generated by buildgen's `py/pybind11-flex` recipe. It ships a
pybind11 extension with optional native tests and an embedded CLI example. Edit
`project.flex.json` (or the plain config emitted after rendering) to toggle the
Catch2/GTest harnesses and CLI support, then re-run `buildgen render` to
regenerate the project.

## Quick Start

```bash
uv sync
uv run pytest
uv build
```

Use `make help` for additional targets (wheel, sdist, clean, etc.).
